blank_issues_enabled: false
contact_links:
    - name: Read the Docs
      url: https://github.com/HesamKashefi/ngx-super-select
      about: Be sure you've read the docs!
    - name: Checkout The Demo
      url: https://stackblitz.com/edit/ngxsuperselect-demo
      about: Have you seen the Demo?